# NOTE: Generated By HttpRunner v3.1.4
# FROM: request_methods/request_with_variables.yml

from httprunner import HttpRunner, Config, Step, RunRequest


class TestStepNameContainVariables(HttpRunner):

    config = (
        Config("request with step name contains variables")
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("step name contains variables: $baz")
            .with_variables(**{"baz": "baz"})
            .get("/get")
            .with_params(**{"baz": "$baz"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]
