# NOTE: Generated By HttpRunner v3.1.4
# FROM: request_methods/request_with_variables.yml


from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseRequestWithVariables(HttpRunner):

    config = (
        Config("request methods testcase with variables")
        .variables(**{"foo1": "testcase_config_bar1", "foo2": "testcase_config_bar2"})
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("evaluate variable")
            .with_variables(
                **{
                    "func": "${get_raw_func()}",
                    "bar": "bar",
                    "foo": "${get_raw_dict()}",
                }
            )
            .post("/post")
            .with_json(
                {"value01": "${eval_var($func)}", "value02": "${eval_var($foo)}"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.data.value01", [2, 0])
            .assert_equal("body.data.value02.foo", "bar")
        ),
    ]


if __name__ == "__main__":
    TestCaseRequestWithVariables().test_start()
