# NOTE: Generated By HttpRunner v3.1.4
# FROM: request_methods/request_with_functions.yml


from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner.configs.mock import mock_settings

mock_settings.mode = True


class TestCaseRequestWithFunctions(HttpRunner):

    config = (
        Config("request with functions")
        .variables(
            **{
                "foo1": "testcase_ref_bar11",
                "foo2": "testsuite_config_bar2",
                "expect_foo1": "testcase_ref_bar11",
                "expect_foo2": "testsuite_config_bar2",
            }
        )
        .base_url("https://postman-echo.com")
        .verify(False)
        .locust_weight(2)
    )

    teststeps = [
        Step(
            RunRequest("post form data")
            .with_variables(**{"foo2": "bar23"})
            .post("/post")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_data("foo2=$foo2")
            .mock(
                {
                    "form": {
                        "foo2": "$foo2",
                        "mock": "mock",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200, "response status code should be 200")
            .assert_equal("body.form.mock", "mock")
        ),
    ]


if __name__ == "__main__":
    TestCaseRequestWithFunctions().test_start()
