# NOTE: Generated By HttpRunner v3.1.4
# FROM: request_methods/request_with_functions.yml


from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner.configs.mock import mock_settings

mock_settings.is_enabled = True


class TestCaseRequestWithMockJs(HttpRunner):

    config = (
        Config("request with mock js")
        .variables(
            **{
                "foo1": "testcase_ref_bar11",
                "foo2": "testsuite_config_bar2",
                "expect_foo1": "testcase_ref_bar11",
                "expect_foo2": "testsuite_config_bar2",
            }
        )
        .base_url("https://postman-echo.com")
        .verify(False)
        .locust_weight(2)
    )

    teststeps = [
        Step(
            RunRequest("mock with json")
            .with_variables(**{"foo2": "bar23", "foo": {"a": "b"}})
            .post("/post")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_json({"mock_js": "test"})
            .mock({"list|2-10": [{"id|+1": 1, "email": "@EMAIL"}]})
            .validate()
            .assert_equal("status_code", 200, "response status code should be 200")
            .assert_length_less_or_equals("body.list", 10)
            .assert_equal("body.list[0].id", 1)
            .assert_equal("body.list[1].id", 2)
            .assert_type_match("body.list[0].email", str)
        ),
    ]


if __name__ == "__main__":
    TestCaseRequestWithMockJs().test_start()
