# NOTE: Generated By HttpRunner v3.1.4
# FROM: request_methods/request_with_functions.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest


@pytest.fixture(autouse=True)
def setup(request):
    """
    Set config variables for testcase.
    """
    config: Config = request.cls.config
    mock_data = BaseExportWithMock().run().get_export_variables()["mock"]
    config.variables(mock_data=mock_data)


class BaseExportWithMock(HttpRunner):

    config = (
        Config("export with mock")
        .variables(
            **{
                "foo1": "testcase_ref_bar11",
            }
        )
        .base_url("https://postman-echo.com")
        .verify(False)
        .export(*["mock"])
        .locust_weight(2)
    )

    teststeps = [
        Step(
            RunRequest("export with mock")
            .with_variables(**{"foo2": "bar23"})
            .post("/post")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_data("foo2=$foo2")
            .mock(
                {
                    "form": {
                        "foo2": "$foo2",
                        "mock": "mock_data",
                    },
                }
            )
            .extract()
            .with_jmespath("body.form.mock", "mock")
            .validate()
            .assert_equal("status_code", 200, "response status code should be 200")
            .assert_equal("body.form.foo2", "bar23")
            .assert_equal("body.form.mock", "mock_data")
        ),
    ]


class TestCaseRequestWithFunctions(HttpRunner):

    config = (
        Config("request with functions")
        .variables(
            **{
                "foo1": "testcase_ref_bar11",
                "foo2": "testsuite_config_bar2",
                "expect_foo1": "testcase_ref_bar11",
                "expect_foo2": "testsuite_config_bar2",
            }
        )
        .base_url("https://postman-echo.com")
        .verify(False)
        .export(*["foo3"])
        .locust_weight(2)
    )

    teststeps = [
        Step(
            RunRequest("post form data")
            .with_variables(**{"foo2": "bar23"})
            .post("/post")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_data("foo2=$foo2")
            .mock(
                {
                    "form": {
                        "foo2": "$foo2",
                        "$mock_data": "mock_data",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200, "response status code should be 200")
            .assert_equal("body.form.foo2", "bar23")
        ),
    ]
