# NOTE: Generated By HttpRunner v3.1.4
# FROM: request_methods/request_with_functions.yml

from httprunner import HttpRunner, Config, Step, RunRequest


class TestRetryArgsAreVars(HttpRunner):

    config = (
        Config("test retry args are vars")
        .variables(
            **{
                "times": "5",
                "interval": "0.5",
                "array": [],
            }
        )
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("get with params and retry 3 times")
            .retry_on_failure("$times", "$interval")
            .post("/post")
            .with_json({"array": "$array"})
            .teardown_hook("${pyexp(array.append(1))}")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.json.array", [1, 1, 1])
        )
    ]
