# NOTE: Generated By HttpRunner v3.1.4
# FROM: request_methods/request_with_testcase_reference.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunTestCase

from examples.postman_echo.parser.request_with_functions_test import (
    TestCaseRequestWithFunctions as RequestWithFunctions,
)


class TestTeardownHookCanUseNestTestcaseExportedVars(HttpRunner):

    config = (
        Config("teardown hook can use nest testcase exported vars")
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunTestCase("teardown hook use nest testcase exported vars")
            .setup_hook("${sleep(0.1)}")
            .call(RequestWithFunctions)
            .teardown_hook("${hook_print($foo3)}")
            .export("app_version_1")
        ),
    ]
