# NOTE: Generated By HttpRunner v3.1.4
# FROM: request_methods/validate_with_variables.yml


from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseExtractedValueContainDollar(HttpRunner):

    config = (
        Config("test parsing when extracted value contains dollar")
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("extracted value contain dollar")
            .post("/post")
            .with_json({"raw_data": {"name": "Get an air fryer for $$9"}})
            .extract()
            .with_jmespath("body.json.raw_data", "_r_raw_data")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("extracted value as function argument")
            .with_variables(**{"name": "${get_raw_data_name($_r_raw_data)}"})
            .post("/post")
            .with_json({"name": "$name"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.json.name", "Get an air fryer for $$9")
        ),
    ]
