# NOTE: Generated By HttpRunner v3.1.4
# FROM: request_methods/validate_with_variables.yml


from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseExtractWithSubExtractor(HttpRunner):

    config = (
        Config("test extract with sub extractor")
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("extracted value contain dollar")
            .with_variables(**{"expression": "body.json.foo"})
            .post("/post")
            .with_json(
                {
                    "foo": "foo:1",
                }
            )
            .extract()
            .with_jmespath(
                "$expression",
                "number",
                lambda x: int(x.split(":")[1]) if isinstance(x, str) else x,
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("$number", 1)
        ),
    ]
