# NOTE: Generated By HttpRunner v3.1.4
# FROM: request_methods/request_with_variables.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRequestWithVariables(HttpRunner):

    config = (
        Config("request methods testcase with variables")
        .variables(**{"foo1": "testcase_config_bar1", "foo2": "testcase_config_bar2"})
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("evaluate variable")
            .with_variables(
                **{
                    "func": "${get_raw_func()}",
                }
            )
            .post("/post")
            .with_json({
                "value": "${evaluate($func)}"
            })
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.data.value", [2, 0])
        ),
    ]


if __name__ == "__main__":
    TestCaseRequestWithVariables().test_start()
