# NOTE: Generated By HttpRunner v3.1.4
# FROM: request_methods/request_with_testcase_reference.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest

from .request_with_functions_test import (
    TestCaseRequestWithFunctions as RequestWithFunctions,
)
from .request_with_testcase_reference_test import (
    TestCaseRequestWithTestcaseReference as RequestWithTestcaseReference,
)


def run_plain_testcase_without_allure() -> dict:
    """
    Run testcase and skip allure data saving.
    """
    return (
        RequestWithFunctions()
        .with_variables(
            {"foo1": "testcase_ref_bar1", "expect_foo1": "testcase_ref_bar1"}
        )
        .set_use_allure(False)
        .run()
        .get_export_variables()
    )


class TestPlainTestcase(HttpRunner):

    config = (
        Config("request methods testcase: reference testcase")
        .variables(
            **{
                "foo1": "testsuite_config_bar1",
                "expect_foo1": "testsuite_config_bar1",
                "expect_foo2": "config_bar2",
                "foo3": run_plain_testcase_without_allure()["foo3"],
            }
        )
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("post form data")
            .with_variables(**{"foo1": "bar1"})
            .post("/post")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_data("foo1=$foo1&foo2=$foo3")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.form.foo1", "bar1")
            .assert_equal("body.form.foo2", "bar21")
        ),
    ]


def run_nested_testcase_without_allure() -> dict:
    """
    Run testcase and skip allure data saving.
    """
    return (
        RequestWithTestcaseReference()
        .set_use_allure(False)
        .run()
        .get_export_variables()
    )


class TestNestedTestcase(HttpRunner):

    config = (
        Config("request methods testcase: reference testcase")
        .variables(
            **{
                "foo1": "testsuite_config_bar1",
                "expect_foo1": "testsuite_config_bar1",
                "expect_foo2": "config_bar2",
                "foo3": run_nested_testcase_without_allure()["foo3"],
            }
        )
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("post form data")
            .with_variables(**{"foo1": "bar1"})
            .post("/post")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_data("foo1=$foo1&foo2=$foo3")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.form.foo1", "bar1")
            .assert_equal("body.form.foo2", "bar21")
        ),
    ]
